### ISSUE TITLE
Delegate call multiple time on single touch on iOS 9

### ISSUE THREAD

**Issue by hagile** [MortimerGoro/MGSwipeTableCell#162] opened 2015-11-16 14:31 UTC
`- (BOOL) swipeTableCell:(MGSwipeTableCell*)cell tappedButtonAtIndex:(NSInteger)index direction:(MGSwipeDirection)direction fromExpansion:(BOOL)fromExpansion`

delegate calls multiple time.

*This is working fine under iOS 7-8*

**Comment by MortimerGoro** [comment] 2015-11-16 19:16
Fixed in 353902c. I will be available in 1.5.2 release

**Comment by hagile** [comment] 2015-11-17 05:45
@MortimerGoro, thanks for the quick response but it still not resolved.

**Comment by hagile** [comment] 2015-11-17 05:53
Please let me know if you want a sample to reproduce this issue.

**Comment by hagile** [comment] 2015-11-17 06:01
A simple workout for this is to recreate buttons everytime !! :(

**Comment by MortimerGoro** [comment] 2015-11-17 09:13
Yes, please send me a sample to reproduce the issue. I can't reproduce with the demos.

**Comment by Ying1986** [comment] 2015-11-17 10:53
Please swipe cell without click, and click swipe buttons several times.

**Comment by MortimerGoro** [comment] 2015-11-17 22:48
It should be fixed in 1.5.3, I remove all the previous buttonClicked selectors now when the new selector is added.

**Comment by BasThomas** [comment] 2015-11-25 12:44
Seems to be fixed in `1.5.3` indeed :+1:

**Closed** 2016-03-03 20:01 UTC

**Comment by GalinaCode** [comment] 2016-03-30 19:12
I'm using MGSwipeTableCell (1.5.4)
But still did not fixed this issue.

**Comment by GalinaCode** [comment] 2016-04-02 15:52
@MortimerGoro 
I fixed this bug.
https://cloudup.com/cKjff_GSldv

**Comment by MortimerGoro** [comment] 2016-04-02 17:18
Just fixed it in 1.5.5

Let me know if it works

**Comment by GalinaCode** [comment] 2016-04-03 00:39
@MortimerGoro 
OK, It is working.
Thanks.
